name: Deploy bucket-antivirus Lambdas

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include: 
          - realm: cyera-prod
            account_id: 112875909405
          - realm: cyera-stage
            account_id: 925314695942
          - realm: cyera-stage-prototype
            account_id: 378356664844
          - realm: dg-stage
            account_id: 708380009554

    steps:
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/GHA-lambda-av-deploy-${{ matrix.realm}}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        run: make archive 

      - name: Deploy to bucket-antivirus-function Lambda
        run: |
          aws lambda update-function-code \
            --function-name bucket-antivirus-function-${{ matrix.realm }} \
            --zip-file fileb://build/lambda.zip \
            --publish

      - name: Get bucket-antivirus-function Lambda updated info
        run: |
          aws lambda get-function-configuration \
            --function-name bucket-antivirus-function-${{ matrix.realm }} \
            --query '{LastModified: LastModified, Version: Version, CodeSha256: CodeSha256}' \
            --output table

      - name: Deploy to bucket-antivirus-update Lambda
        run: |
          aws lambda update-function-code \
            --function-name bucket-antivirus-update-${{ matrix.realm }} \
            --zip-file fileb://build/lambda.zip \
            --publish

      - name: Get bucket-antivirus-update Lambda updated info
        run: |
          aws lambda get-function-configuration \
            --function-name bucket-antivirus-update-${{ matrix.realm }} \
            --query '{LastModified: LastModified, Version: Version, CodeSha256: CodeSha256}' \
            --output table